### ISSUE TITLE
3.0.0 Release Tracker

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#515]
- [x] 100% Test Passing on Travis CI
    - [x] Python 3.5
    - [x] Python 3.6
    - [x] Python 3.7
- [x] 100% Test Coverage
- [x] API Documentation Builds (Read The Docs)
    - [x] 2.99
- [x] Developer Documentation (Gitbook)
    - [x] stable/2.99
- [x] Docker Image Builds (Docker Hub)
    - [x] datafolklabs/cement:X
    - [x] datafolklabs/cement:X.Y
    - [x] datafolklabs/cement:X.Y.Z
