### ISSUE TITLE
3.0.2 Stable Release Tracker

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#543]
- [x] Git Tag
    - [x] X
    - [x] X.Y
    - [x] X.Y.Z
- [x] Git Merge to Version Branch
    - [x] stable/X.Y
- [x] 100% Test Passing on Travis CI
    - [x] Python 3.5
    - [x] Python 3.6
    - [x] Python 3.7
- [x] 100% Test Coverage
- [x] API Documentation Builds (Read The Docs)
    - [x] X.Y
- [x] Developer Documentation (Gitbook)
    - [x] stable/X.Y
    - [x] Update Change Log and Release Notes
- [x] Docker Image Builds (Docker Hub)
    - [x] datafolklabs/cement:X
    - [x] datafolklabs/cement:X.Y
    - [x] datafolklabs/cement:X.Y.Z
- [x] PyPi Distribution
