### ISSUE TITLE
3.0.6 Stable Release Tracker

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#615]
- [x] Git Tag
    - [x] X
    - [x] X.Y
    - [x] X.Y.Z
- [x] Git Merge to Version Branch
    - stable/X.Y
- [x] 100% Test Passing on Travis CI
    - [x] Python 3.7
    - [x] Python 3.8
    - [x] Python 3.9
- [x] 100% Test Coverage
- [x] API Documentation Builds (Read The Docs)
    - [x] X.Y
- [x] Developer Documentation (Gitbook)
    - [x] stable/X.Y
    - [x] Update Change Log and Release Notes
- [x] Docker Image Builds (Docker Hub)
    - [x] datafolklabs/cement:X
    - [x] datafolklabs/cement:X.Y
    - [x] datafolklabs/cement:X.Y.Z
- [x]  PyPi Distribution
