### ISSUE TITLE
3.0.10 Stable Release Tracker

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#676]
- [x] 100% Test Passing on Travis CI
    - [x] Python 3.8
    - [x] Python 3.9
    - [x] Python 3.10
    - [x] Python 3.11
    - [x] Python 3.12
- [x] 100% Test Coverage
- [x] Core Tests on Windows
- [x] Cement CLI Smoke Tests
    - [x] Linux
    - [x] macOS
    - [x] Windows
- [x] Git Builds 
    - Tags:
        - [x] X
        - [x] X.Y
        - [x] X.Y.Z
- [x] Git Merge to Version Branch
    - stable/X.Y
- [ ] API Documentation Builds (Read The Docs)
    - [ ] X.Y
- [x] Developer Documentation (Gitbook)
    - [x] stable/X.Y
    - [x] Update Change Log
    - [x] Update Release Notes
    - [x] Update Deprecations
    - [x] Update relevant docs related to changes/enhancements
- [x] Docker Image Builds (Docker Hub)
    - [x] datafolklabs/cement:X
    - [x] datafolklabs/cement:X.Y
    - [x] datafolklabs/cement:X.Y.Z
    - Archs:
        - linux/amd64
        - linux/arm64
- [x] PyPi Distribution
- [x] Notify mailing list
- [x] Notify Slack channel

**Comment by derks** [comment]
Core Tests on Windows:

```
---------- coverage: platform win32, python 3.12.1-final-0 -----------
Name                          Stmts   Miss  Cover
-------------------------------------------------
cement\core\__init__.py           0      0   100%
cement\core\arg.py               13      0   100%
cement\core\backend.py            0      0   100%
cement\core\cache.py             17      0   100%
cement\core\config.py            40      0   100%
cement\core\controller.py        11      0   100%
cement\core\deprecations.py       7      0   100%
cement\core\exc.py               14      0   100%
cement\core\extension.py         44      0   100%
cement\core\foundation.py       683     32    95%
cement\core\handler.py          121      1    99%
cement\core\hook.py              37      0   100%
cement\core\interface.py         38      0   100%
cement\core\log.py               21      0   100%
cement\core\mail.py              25      3    88%
cement\core\meta.py              17      0   100%
cement\core\output.py            11      0   100%
cement\core\plugin.py            19      0   100%
cement\core\template.py         159     62    61%
-------------------------------------------------
TOTAL                          1277     98    92%
Coverage HTML written to dir coverage-report

==================================== 133 passed, 1 skipped, 1477 warnings in 4.67s ====================================
```

**Comment by derks** [comment]
RTD build is failing... 

- https://github.com/datafolklabs/cement/issues/677
