### ISSUE TITLE
3.0.12 Stable Release Tracker

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#729]
- [x] 100% Test Passing on Travis CI
    - [x] Python 3.8
    - [x] Python 3.9
    - [x] Python 3.10
    - [x] Python 3.11
    - [x] Python 3.12
    - [x] Python 3.13
- [x] 100% Test Coverage and Compliance (Ruff/MyPy)
- [x] Core Tests on Windows
- [x] Cement CLI Smoke Tests
    - [x] Linux
    - [x] macOS
    - [x] Windows
- [x] Git Builds 
    - Tags:
        - [x] X
        - [x] X.Y
        - [x] X.Y.Z
- [x] Git Merge to Version Branch
    - stable/X.Y
- [x] API Documentation Builds (Read The Docs)
    - [x] X.Y
- [x] Developer Documentation (Gitbook)
    - [x] stable/X.Y
    - [x] Update Change Log
    - [x] Update Release Notes
    - [x] Update Deprecations
    - [x] Update relevant docs related to changes/enhancements
- [x] Docker Image Builds (Docker Hub)
    - [x] datafolklabs/cement:X
    - [x] datafolklabs/cement:X.Y
    - [x] datafolklabs/cement:X.Y.Z
    - Archs:
        - linux/amd64
        - linux/arm64
- [x] PyPi Distribution
- [ ] Notify mailing list
- [ ] Notify Slack channel

**Comment by derks** [comment]
CLI Smoke Tests:

```
derks@macbook cement $ ./scripts/cli-smoke-test.sh
output in tmp/cli-smoke-test.out
Building sdist...
Built sdist at /src/dist/cement-3.0.11.tar.gz
Building wheel from sdist...
Built wheel at /src/dist/cement-3.0.11-py3-none-any.whl
INFO: PDM 2.15.4 is installed, while 2.20.1 is available.
Please run `pipx upgrade pdm` to upgrade.
Run `pdm config check_update false` to disable the check.
python 3.8 . . . ok
python 3.9 . . . ok
python 3.10 . . . ok
python 3.11 . . . ok
python 3.12 . . . ok
python 3.13 . . . ok
```

**Comment by derks** [comment]
Unit Tests: 

```
|> cement-py313 <| src # make test
pdm run ruff check cement/ tests/
All checks passed!
pdm run mypy
Success: no issues found in 51 source files
pdm run pytest --cov=cement tests
==================================================== test session starts ====================================================
platform linux -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0 -- /src/.venv/bin/python
cachedir: .pytest_cache
rootdir: /src
configfile: pyproject.toml
plugins: cov-5.0.0
collected 304 items

---------- coverage: platform linux, python 3.13.0-final-0 -----------
Name                                 Stmts   Miss    Cover
----------------------------------------------------------
cement/__init__.py                       9      0  100.00%
cement/cli/__init__.py                   0      0  100.00%
cement/cli/controllers/__init__.py       0      0  100.00%
cement/cli/controllers/base.py          11      0  100.00%
cement/cli/main.py                      27      0  100.00%
cement/cli/templates/__init__.py         0      0  100.00%
cement/core/__init__.py                  0      0  100.00%
cement/core/arg.py                      15      0  100.00%
cement/core/backend.py                   0      0  100.00%
cement/core/cache.py                    19      0  100.00%
cement/core/config.py                   42      0  100.00%
cement/core/controller.py               14      0  100.00%
cement/core/deprecations.py              7      0  100.00%
cement/core/exc.py                      15      0  100.00%
cement/core/extension.py                47      0  100.00%
cement/core/foundation.py              690      0  100.00%
cement/core/handler.py                 125      0  100.00%
cement/core/hook.py                     41      0  100.00%
cement/core/interface.py                42      0  100.00%
cement/core/log.py                      22      0  100.00%
cement/core/mail.py                     28      0  100.00%
cement/core/meta.py                     18      0  100.00%
cement/core/output.py                   13      0  100.00%
cement/core/plugin.py                   21      0  100.00%
cement/core/template.py                161      0  100.00%
cement/ext/__init__.py                   0      0  100.00%
cement/ext/ext_alarm.py                 24      0  100.00%
cement/ext/ext_argparse.py             319      0  100.00%
cement/ext/ext_colorlog.py              45      0  100.00%
cement/ext/ext_configparser.py          61      0  100.00%
cement/ext/ext_daemon.py                69      0  100.00%
cement/ext/ext_dummy.py                 56      0  100.00%
cement/ext/ext_generate.py             121      0  100.00%
cement/ext/ext_jinja2.py                45      0  100.00%
cement/ext/ext_json.py                  61      0  100.00%
cement/ext/ext_logging.py              149      0  100.00%
cement/ext/ext_memcached.py             48      0  100.00%
cement/ext/ext_mustache.py              42      0  100.00%
cement/ext/ext_plugin.py                94      0  100.00%
cement/ext/ext_print.py                 38      0  100.00%
cement/ext/ext_redis.py                 41      0  100.00%
cement/ext/ext_scrub.py                 36      0  100.00%
cement/ext/ext_smtp.py                  94      0  100.00%
cement/ext/ext_tabulate.py              28      0  100.00%
cement/ext/ext_watchdog.py              82      0  100.00%
cement/ext/ext_yaml.py                  55      0  100.00%
cement/utils/__init__.py                 0      0  100.00%
cement/utils/fs.py                      69      0  100.00%
cement/utils/misc.py                   100      0  100.00%
cement/utils/shell.py                  129      0  100.00%
cement/utils/test.py                     7      0  100.00%
cement/utils/version.py                 34      0  100.00%
----------------------------------------------------------
TOTAL                                 3214      0  100.00%
Coverage HTML written to dir coverage-report

============================================ 304 passed, 1657 warnings in 43.17s ============================================
```
